### ISSUE TITLE
New 0.1.8b0 version

### ISSUE THREAD

**Issue by pfreixes** [acsylla/acsylla#71]
Lets publish our first beta release of acsylla, i would propose for going for `0.1.8b0` wait a bit and for the next release make the GA

WDYT @whiteluna ?

**Comment by whiteluna** [comment]
@pfreixes  What abbr "GA" mean?)

BTW for a beta release i would like to add build wheel for aarh64 and update build_manylinux2010_wheel.sh for use manylinux2014 image because support for manylinux2010  has ended https://github.com/pypa/manylinux/issues/1281  and updete uvloop for latest version [1.44.2 (Stable)](https://github.com/libuv/libuv/releases/tag/v1.44.2)

**Comment by pfreixes** [comment]
Sorty Global Availability, oks perfect lets wait until you can provide support for `aarch64` lets keep this ticket open until then

**Comment by pfreixes** [comment]
This can be closed, right? new version already available
